version: 2.1

orbs:
   azure-acr: circleci/azure-acr@x.y.z

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    jobs:
      - checkout
      - setup_remote_docker
      - run: docker build -t codingblog-frontend:latest .
      - run: docker tag codingblog-frontend codingsimon/codingblog-frontend
      - run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin $REGISTRY_HOST
      - run: docker push codingsimon/codingblog-frontend
               
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
