version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      name: Copy Service Test Results
      command: |
        docker build -t codingsimon/codingblog-frontend:latest .
        docker tag codingblog-frontend codingsimon/codingblog-frontend
        docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin $REGISTRY_HOST
        docker push codingsimon/codingblog-frontend:latest
      
               
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
