version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: ls

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
