version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t codingblog-frontend:latest .
  publish-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin $REGISTRY_HOST
            docker push codingblog-frontend


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - publish-latest
