version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t codingblog-frontend:latest .
      - run: docker tag codingblog-frontend codingsimon/codingblog-frontend
      - run: az acr login --name codingsimon
      - run: docker push codingsimon/codingblog-frontend


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
