version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t codingsimon/codingblog-frontend:latest .
      - run: docker tag codingblog-frontend codingsimon/codingblog-frontend
      - run: docker login $REGISTRY_HOST -u $DOCKER_USER -p $DOCKER_PASSWORD && docker push codingsimon/codingblog-frontend:latest
workflows:
  version: 2
  build:
    jobs:
      - build
