on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - uses: azure/docker-login@v1
          with:
            login-server: codingsimon.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build .t codingsimon.azurecr.io/codingblog-react-frontend:${{ github.sha }}
            docker push codingsimon.azurecr.io/codingblog-react-frontend:${{ github.sha }}
